export default function (invite_id) {
  var strVar = '';
  strVar += '<div style="background-color:#f3f3f3;padding:40px 0">';
  strVar += '';
  strVar += '<div style="width:400px;margin:0 auto;background-color:#fff;font-family:Helvetica Neue,Helvetica,sans-serif;text-align:left;line-height:1.5em;border-radius:3px;padding:30px 30px 20px 30px;color:#666;font-size:16px">';
  strVar += '';
  strVar += '<h2 style="text-align:center;margin:10px 0 0px 0;padding:0;color:#FF0000">OOP<\/h2>';
  strVar += '<h4 style="text-align:center;margin:0px 0 30px 0;padding:0;color:#FF0000">Ounce of Prevention<\/h4>';
  strVar += ' ';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '<p><strong>Hello!<\/strong><\/p>';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '<p>You have been invited to the Ounce of Prevention app to help with your situation<\/p>';
  strVar += '';
  strVar += '';
  strVar += '<p>Accept your invitation by going to the link below:</p>';
  strVar += `localhost:5001/invite/${invite_id}`;
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '<p>– the OOP team<\/p>';
  strVar += '';
  strVar += '';
  strVar += '';
  strVar += '';

  return strVar;
}
